Assignment 4
FacultadInformatica-LinkedData/Curso2022-2023-DataScience pull request #103
Opened 2022-10-24 14:58 UTC by davidhernandog

2022-10-24 21:08 UTC, dgarijo requested changes
small changes required still

2022-10-24 21:08 UTC, dgarijo commented on Assignment4/davidhernandog_D21C027/task06.py
> +g.add((ns.UPM, vcard.member, ns.JohnSmith))
vcard does not define `member`. Find another vocabulary, or define your own property

2022-10-24 21:08 UTC, dgarijo commented on Assignment4/davidhernandog_D21C027/task07.py
> +  print(x)
You are listing all subclasses of person and then only the subclasses of the first subclass

2022-10-25 10:42 UTC, davidhernandog commented
I just changed it

2022-10-25 11:33 UTC, dgarijo approved these changes

2022-10-25 11:34 UTC, merged