Assignment 2 OK
FacultadInformatica-LinkedData/Curso2022-2023-DataScience pull request #28
Opened 2022-09-26 13:38 UTC by marioruiz2003

2022-09-26 20:01 UTC, ocorcho requested changes

2022-09-26 20:01 UTC, ocorcho commented on Assignment2/marioruiz2003-MarioRuiz.ttl
> +     rdfs:atTime "2010-06-12T12:00:12".
Wrong use of rdfs prefix, and you should add a datatype to the strings hereand in the previous triple.

2022-09-26 20:02 UTC, ocorcho commented
I was asking for chhanges, but now I realised that you are also deleting some of your other students files. This is not acceptable. Closing this pull request.

2022-09-26 20:02 UTC, closed without merging

2022-09-26 20:33 UTC, marioruiz2003 commented
I did not know I was deleting other student files. I am not used to using
this platform, while I was trying to upload my answer, in GitHub Desktop I
was asked to pull origin and when I accepted I had downloaded 66 commits
and then I don't know why I have my partner files in my repository, so I
deleted them. I did not know that this would delete it from GitHub.  Why
would I delete my partners files? Please I was not conscious that this
could happen. Would you let me do another pull request? Let me know.

El lun, 26 sept 2022 a las 22:02, Oscar Corcho ***@***.***>)
escribió:

> I was asking for chhanges, but now I realised that you are also deleting
> some of your other students files. This is not acceptable. Closing this
> pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FacultadInformatica-LinkedData/Curso2022-2023-DataScience/pull/28#issuecomment-1258552192>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A26QEAMQLEMKKSZ7P3YTWJ3WAH6MRANCNFSM6AAAAAAQVZ23FE>
> .
> You are receiving this because you authored the thread.Message ID:
> <FacultadInformatica-LinkedData/Curso2022-2023-DataScience/pull/28/c1258552192
> @github.com>
>

2022-09-27 08:43 UTC, dgarijo commented
If you synchronize from origin, then you delete and do a pull request you are in fact proposing to delete existing files.
Oscar did not say you can't do another pull request. Open a new one without deleting the files from your classmates